#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    systemctl daemon-reload || true
    rm -f /lib/systemd/system/dispenser.service
fi

if [ "$1" = "purge" ]; then
    # Remove the dispenser user and its home directory
    userdel -r dispenser || true
    rm -rf /opt/dispenser
fi
