#!/bin/sh
set -e

# Create the 'compose-watcher' user and home directory if it doesn't exist
if ! id -u compose-watcher > /dev/null 2>&1; then
    useradd -r -d /opt/compose-watcher -s /bin/false compose-watcher
    mkdir -p /opt/compose-watcher
    chown compose-watcher:compose-watcher /opt/compose-watcher
fi

# Create the compose-watcher.toml file if it doesn't exist
if [ ! -f /opt/compose-watcher/compose-watcher.toml ]; then
    echo "delay=60 # Will watch for updates every 60 seconds" >> /opt/compose-watcher/compose-watcher.toml
    chown compose-watcher:compose-watcher /opt/compose-watcher/compose-watcher.toml
fi

# Restart the service on upgrade
if [ "$1" = "configure" ]; then
    systemctl daemon-reload || true
    systemctl enable compose-watcher.service || true
    systemctl start compose-watcher.service || true
fi
