#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    systemctl daemon-reload || true
    rm -f /lib/systemd/system/compose-watcher.service
fi

rm -rf /usr/local/bin/compose-watcher

if [ "$1" = "purge" ]; then
    # Remove the compose-watcher user and its home directory
    userdel -r compose-watcher || true
    rm -rf /opt/compose-watcher
fi
