name: Build Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.os }} Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [debian-12, debian-13, ubuntu-24, rhel-8, rhel-9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.42.4

      - name: Build package
        run: just build-${{ matrix.os }}

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: dispenser-${{ matrix.os }}
          path: |
            *.deb
            rpmout/RPMS/x86_64/*.rpm
